# Generated by Django 4.2.5 on 2023-09-22 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=500)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200000, null=True, verbose_name='meeting title')),
                ('password', models.CharField(blank=True, max_length=20, null=True, verbose_name='meeting password')),
                ('link', models.UUIDField(blank=True, default=uuid.UUID('b71b2570-0623-4eef-8e87-8a778fe37c80'), null=True, unique=True, verbose_name='meeting link')),
                ('offer', models.CharField(verbose_name="creator's offer")),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', related_query_name='meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'meeting',
                'verbose_name_plural': 'meetings',
                'db_table': 'meeting',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.BinaryField(max_length=12, null=True)),
                ('profile_picture', models.ImageField(null=True, upload_to='profile_images/')),
                ('user_queue', models.CharField(blank=True, null=True)),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='MeetingJoiner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting_link', models.CharField(blank=True, null=True, verbose_name='link')),
                ('meeting_pass', models.CharField(blank=True, null=True)),
                ('answer', models.CharField(verbose_name="meeting joiner's answer")),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('joiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_meetings', related_query_name='joined_meetings', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joiners', related_query_name='joiners', to='socket_server.meeting')),
            ],
            options={
                'db_table': 'meeting_joiner',
            },
        ),
    ]
