# Generated by Django 4.2.5 on 2023-10-02 15:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('socket_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='link',
            field=models.UUIDField(blank=True, default=uuid.UUID('d1a0f30e-e055-4e5f-849c-a94177dd2d57'), null=True, unique=True, verbose_name='meeting link'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='offer',
            field=models.JSONField(verbose_name="creator's offer"),
        ),
        migrations.AlterField(
            model_name='meetingjoiner',
            name='answer',
            field=models.JSONField(verbose_name="meeting joiner's answer"),
        ),
    ]
