# Generated by Django 4.2.5 on 2023-09-22 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('socket_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200000, null=True, verbose_name='meeting title')),
                ('password', models.CharField(blank=True, max_length=20, null=True, verbose_name='meeting password')),
                ('link', models.UUIDField(blank=True, default=uuid.UUID('d0e6123a-eed9-48e0-96c4-b01329201199'), null=True, unique=True, verbose_name='meeting link')),
                ('offer', models.CharField(verbose_name="creator's offer")),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', related_query_name='meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'meeting',
                'verbose_name_plural': 'meetings',
                'db_table': 'meeting',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='user_queue',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MeetingJoiner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting_link', models.CharField(blank=True, null=True, verbose_name='link')),
                ('meeting_pass', models.CharField(blank=True, null=True)),
                ('answer', models.CharField(verbose_name="meeting joiner's answer")),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('joiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_meetings', related_query_name='joined_meetings', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joiners', related_query_name='joiners', to='socket_server.meeting')),
            ],
        ),
    ]
